# Data extraction

Created by Guillermo Arredondo Renero

Creation date: May 3, 2026  
Last updated: May 3, 2026

**Main objective**: Extracting dataset _Default Credit Clients_ from UC Irivine Machine Learning Repository.

In [1]:
# -------------------- Libraries ------------------
## Directories and system
import os 

## Data usage
import pandas as pd
import numpy as np

## Data repository
from ucimlrepo import fetch_ucirepo

In [2]:
# -------------------- Directories ------------------
# Get main directory
CURRENT_DIR = os.getcwd()
MAIN_DIR = os.path.dirname(CURRENT_DIR)
# Create data directory
os.makedirs(os.path.join(MAIN_DIR, 'data', 'raw'), exist_ok=True)

In [3]:
# fetch dataset
default_of_credit_card_clients = fetch_ucirepo(id=350) 

# Read data
X = default_of_credit_card_clients.data.features
y = default_of_credit_card_clients.data.targets
print(f"Shapes - X: {X.shape}, y: {y.shape}")

Shapes - X: (30000, 23), y: (30000, 1)

In [4]:
default_of_credit_card_clients.data.ids

          ID
0          1
1          2
2          3
3          4
4          5
...      ...
29995  29996
29996  29997
29997  29998
29998  29999
29999  30000

[30000 rows x 1 columns]

Podemos igorar el ID ya que es únicamente de referencia y no se utilizará para el modelo

In [5]:
# Merge into a single dataframe
df = pd.concat([X, y], axis=1)
df.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [6]:
# metadata 
print(default_of_credit_card_clients.metadata)

{'uci_id': 350, 'name': 'Default of Credit Card Clients', 'repository_url': 'https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients', 'data_url': 'https://archive.ics.uci.edu/static/public/350/data.csv', 'abstract': "This research aimed at the case of customers' default payments in Taiwan and compares the predictive accuracy of probability of default among six data mining methods.", 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 30000, 'num_features': 23, 'feature_types': ['Integer', 'Real'], 'demographics': ['Sex', 'Education Level', 'Marital Status', 'Age'], 'target_col': ['Y'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2009, 'last_updated': 'Fri Mar 29 2024', 'dataset_doi': '10.24432/C55S3H', 'creators': ['I-Cheng Yeh'], 'intro_paper': {'ID': 365, 'type': 'NATIVE', 'title': 'The comparisons of data mining techniques for the predictive accuracy of probability of default of credit card clients', 'authors': 'I. Yeh, Che-hui Lien', 'venue': 'Expert systems with applications', 'year': 2009, 'journal': None, 'DOI': '10.1016/j.eswa.2007.12.020', 'URL': 'https://www.semanticscholar.org/paper/1cacac4f0ea9fdff3cd88c151c94115a9fddcf33', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "This research aimed at the case of customers' default payments in Taiwan and compares the predictive accuracy of probability of default among six data mining methods. From the perspective of risk management, the result of predictive accuracy of the estimated probability of default will be more valuable than the binary result of classification - credible or not credible clients. Because the real probability of default is unknown, this study presented the novel Sorting Smoothing Method to estimate the real probability of default. With the real probability of default as the response variable (Y), and the predictive probability of default as the independent variable (X), the simple linear regression result (Y = A + BX) shows that the forecasting model produced by artificial neural network has the highest coefficient of determination; its regression intercept (A) is close to zero, and regression coefficient (B) to one. Therefore, among the six data mining techniques, artificial neural network is the only one that can accurately estimate the real probability of default.", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'This research employed a binary variable, default payment (Yes = 1, No = 0), as the response variable. This study reviewed the literature and used the following 23 variables as explanatory variables:\r\nX1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit.\r\nX2: Gender (1 = male; 2 = female).\r\nX3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others).\r\nX4: Marital status (1 = married; 2 = single; 3 = others).\r\nX5: Age (year).\r\nX6 - X11: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as follows: X6 = the repayment status in September, 2005; X7 = the repayment status in August, 2005; . . .;X11 = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above.\r\nX12-X17: Amount of bill statement (NT dollar). X12 = amount of bill statement in September, 2005; X13 = amount of bill statement in August, 2005; . . .; X17 = amount of bill statement in April, 2005. \r\nX18-X23: Amount of previous payment (NT dollar). X18 = amount paid in September, 2005; X19 = amount paid in August, 2005; . . .;X23 = amount paid in April, 2005.\r\n', 'citation': None}}

In [7]:
# variable information 
print(default_of_credit_card_clients.variables)

   name     role     type      demographic                 description units  \
0    ID       ID  Integer              NaN                         NaN  None
1    X1  Feature  Integer              NaN                   LIMIT_BAL  None
2    X2  Feature  Integer              Sex                         SEX  None
3    X3  Feature  Integer  Education Level                   EDUCATION  None
4    X4  Feature  Integer   Marital Status                    MARRIAGE  None
5    X5  Feature  Integer              Age                         AGE  None
6    X6  Feature  Integer              NaN                       PAY_0  None
7    X7  Feature  Integer              NaN                       PAY_2  None
8    X8  Feature  Integer              NaN                       PAY_3  None
9    X9  Feature  Integer              NaN                       PAY_4  None
10  X10  Feature  Integer              NaN                       PAY_5  None
11  X11  Feature  Integer              NaN                       PAY_6  None
12  X12  Feature  Integer              NaN                   BILL_AMT1  None
13  X13  Feature  Integer              NaN                   BILL_AMT2  None
14  X14  Feature  Integer              NaN                   BILL_AMT3  None
15  X15  Feature  Integer              NaN                   BILL_AMT4  None
16  X16  Feature  Integer              NaN                   BILL_AMT5  None
17  X17  Feature  Integer              NaN                   BILL_AMT6  None
18  X18  Feature  Integer              NaN                    PAY_AMT1  None
19  X19  Feature  Integer              NaN                    PAY_AMT2  None
20  X20  Feature  Integer              NaN                    PAY_AMT3  None
21  X21  Feature  Integer              NaN                    PAY_AMT4  None
22  X22  Feature  Integer              NaN                    PAY_AMT5  None
23  X23  Feature  Integer              NaN                    PAY_AMT6  None
24    Y   Target   Binary              NaN  default payment next month  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no
15             no
16             no
17             no
18             no
19             no
20             no
21             no
22             no
23             no
24             no

In [8]:
vars = default_of_credit_card_clients.variables[['name', 'description']]
vars.set_index('name', inplace=True)
df.rename(columns=vars.to_dict()['description'], inplace=True)
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [9]:
# -------------------- Data Loading ------------------
df.to_csv(os.path.join(MAIN_DIR, 'data', 'raw', 'credit_dataset.csv'), index=False)